"""create messages table

Revision ID: 52d5fb7451a7
Revises: ccd3451f6f0c
Create Date: 2025-06-14 19:58:06.074219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d5fb7451a7'
down_revision = 'ccd3451f6f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
